import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BuilderInit from "@/components/builder-init";
import RegistryMount from "@/components/registry-mount";
import I18nProvider from "@/components/i18n-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Builder.io nextjs ssr",
  description: "Generated by vercel using fusion AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BuilderInit />
        <RegistryMount />
        <I18nProvider>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
